// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: pingService.proto
//
import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

public class PingServiceClient(
  private val client: ProtocolClientInterface,
) : PingServiceClientInterface {
  override suspend fun serviceAvailable(request: PingServiceOuterClass.Ping, headers: Headers): ResponseMessage<PingServiceOuterClass.Pong> = client.unary(
    request,
    headers,
    MethodSpec(
    "PingService/ServiceAvailable",
      PingServiceOuterClass.Ping::class,
      PingServiceOuterClass.Pong::class,
      StreamType.UNARY,
    ),
  )

}
