package nl.openov.ovinfoperstem.proto// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: mainService.proto
//
import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.ServerOnlyStreamInterface
import com.connectrpc.StreamType
import com.google.protobuf.Empty

public class TravelChatServiceClient(
  private val client: ProtocolClientInterface,
) : TravelChatServiceClientInterface {
  override suspend fun sendInput(request: UserInputOuterClass.UserInput, headers: Headers): ResponseMessage<UserInputOuterClass.UserInputResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "TravelChatService/sendInput",
      UserInputOuterClass.UserInput::class,
      UserInputOuterClass.UserInputResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getFeedback(headers: Headers): ServerOnlyStreamInterface<Empty, FeedbackOuterClass.Feedback> = client.serverStream(
    headers,
    MethodSpec(
    "TravelChatService/getFeedback",
      com.google.protobuf.Empty::class,
      FeedbackOuterClass.Feedback::class,
      StreamType.SERVER,
    ),
  )

}
