package nl.openov.ovinfoperstem.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: userInput.proto
// Protobuf Java Version: 4.29.3

public final class UserInputOuterClass {
  private UserInputOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      UserInputOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
     * @return Whether the stringInput field is set.
     */
    boolean hasStringInput();
    /**
     * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
     * @return The stringInput.
     */
    UserInputOuterClass.StringInput getStringInput();
    /**
     * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
     */
    UserInputOuterClass.StringInputOrBuilder getStringInputOrBuilder();

    /**
     * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
     * @return Whether the audioInput field is set.
     */
    boolean hasAudioInput();
    /**
     * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
     * @return The audioInput.
     */
    UserInputOuterClass.AudioInput getAudioInput();
    /**
     * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
     */
    UserInputOuterClass.AudioInputOrBuilder getAudioInputOrBuilder();

    UserInputOuterClass.UserInput.InputCase getInputCase();
  }
  /**
   * Protobuf type {@code UserInput}
   */
  public static final class UserInput extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserInput)
      UserInputOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        UserInput.class.getName());
    }
    // Use UserInput.newBuilder() to construct.
    private UserInput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserInput() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserInputOuterClass.internal_static_UserInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserInputOuterClass.internal_static_UserInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserInputOuterClass.UserInput.class, UserInputOuterClass.UserInput.Builder.class);
    }

    private int inputCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object input_;
    public enum InputCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      STRINGINPUT(1),
      AUDIOINPUT(2),
      INPUT_NOT_SET(0);
      private final int value;
      private InputCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InputCase valueOf(int value) {
        return forNumber(value);
      }

      public static InputCase forNumber(int value) {
        switch (value) {
          case 1: return STRINGINPUT;
          case 2: return AUDIOINPUT;
          case 0: return INPUT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public InputCase
    getInputCase() {
      return InputCase.forNumber(
          inputCase_);
    }

    public static final int STRINGINPUT_FIELD_NUMBER = 1;
    /**
     * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
     * @return Whether the stringInput field is set.
     */
    @java.lang.Override
    public boolean hasStringInput() {
      return inputCase_ == 1;
    }
    /**
     * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
     * @return The stringInput.
     */
    @java.lang.Override
    public UserInputOuterClass.StringInput getStringInput() {
      if (inputCase_ == 1) {
         return (UserInputOuterClass.StringInput) input_;
      }
      return UserInputOuterClass.StringInput.getDefaultInstance();
    }
    /**
     * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
     */
    @java.lang.Override
    public UserInputOuterClass.StringInputOrBuilder getStringInputOrBuilder() {
      if (inputCase_ == 1) {
         return (UserInputOuterClass.StringInput) input_;
      }
      return UserInputOuterClass.StringInput.getDefaultInstance();
    }

    public static final int AUDIOINPUT_FIELD_NUMBER = 2;
    /**
     * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
     * @return Whether the audioInput field is set.
     */
    @java.lang.Override
    public boolean hasAudioInput() {
      return inputCase_ == 2;
    }
    /**
     * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
     * @return The audioInput.
     */
    @java.lang.Override
    public UserInputOuterClass.AudioInput getAudioInput() {
      if (inputCase_ == 2) {
         return (UserInputOuterClass.AudioInput) input_;
      }
      return UserInputOuterClass.AudioInput.getDefaultInstance();
    }
    /**
     * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
     */
    @java.lang.Override
    public UserInputOuterClass.AudioInputOrBuilder getAudioInputOrBuilder() {
      if (inputCase_ == 2) {
         return (UserInputOuterClass.AudioInput) input_;
      }
      return UserInputOuterClass.AudioInput.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (inputCase_ == 1) {
        output.writeMessage(1, (UserInputOuterClass.StringInput) input_);
      }
      if (inputCase_ == 2) {
        output.writeMessage(2, (UserInputOuterClass.AudioInput) input_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (inputCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (UserInputOuterClass.StringInput) input_);
      }
      if (inputCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (UserInputOuterClass.AudioInput) input_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserInputOuterClass.UserInput)) {
        return super.equals(obj);
      }
      UserInputOuterClass.UserInput other = (UserInputOuterClass.UserInput) obj;

      if (!getInputCase().equals(other.getInputCase())) return false;
      switch (inputCase_) {
        case 1:
          if (!getStringInput()
              .equals(other.getStringInput())) return false;
          break;
        case 2:
          if (!getAudioInput()
              .equals(other.getAudioInput())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (inputCase_) {
        case 1:
          hash = (37 * hash) + STRINGINPUT_FIELD_NUMBER;
          hash = (53 * hash) + getStringInput().hashCode();
          break;
        case 2:
          hash = (37 * hash) + AUDIOINPUT_FIELD_NUMBER;
          hash = (53 * hash) + getAudioInput().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserInputOuterClass.UserInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.UserInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.UserInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.UserInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.UserInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.UserInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.UserInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserInputOuterClass.UserInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserInputOuterClass.UserInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserInputOuterClass.UserInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserInputOuterClass.UserInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserInputOuterClass.UserInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserInputOuterClass.UserInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserInput)
        UserInputOuterClass.UserInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserInputOuterClass.internal_static_UserInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserInputOuterClass.internal_static_UserInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserInputOuterClass.UserInput.class, UserInputOuterClass.UserInput.Builder.class);
      }

      // Construct using UserInputOuterClass.UserInput.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (stringInputBuilder_ != null) {
          stringInputBuilder_.clear();
        }
        if (audioInputBuilder_ != null) {
          audioInputBuilder_.clear();
        }
        inputCase_ = 0;
        input_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserInputOuterClass.internal_static_UserInput_descriptor;
      }

      @java.lang.Override
      public UserInputOuterClass.UserInput getDefaultInstanceForType() {
        return UserInputOuterClass.UserInput.getDefaultInstance();
      }

      @java.lang.Override
      public UserInputOuterClass.UserInput build() {
        UserInputOuterClass.UserInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UserInputOuterClass.UserInput buildPartial() {
        UserInputOuterClass.UserInput result = new UserInputOuterClass.UserInput(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(UserInputOuterClass.UserInput result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(UserInputOuterClass.UserInput result) {
        result.inputCase_ = inputCase_;
        result.input_ = this.input_;
        if (inputCase_ == 1 &&
            stringInputBuilder_ != null) {
          result.input_ = stringInputBuilder_.build();
        }
        if (inputCase_ == 2 &&
            audioInputBuilder_ != null) {
          result.input_ = audioInputBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserInputOuterClass.UserInput) {
          return mergeFrom((UserInputOuterClass.UserInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserInputOuterClass.UserInput other) {
        if (other == UserInputOuterClass.UserInput.getDefaultInstance()) return this;
        switch (other.getInputCase()) {
          case STRINGINPUT: {
            mergeStringInput(other.getStringInput());
            break;
          }
          case AUDIOINPUT: {
            mergeAudioInput(other.getAudioInput());
            break;
          }
          case INPUT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getStringInputFieldBuilder().getBuilder(),
                    extensionRegistry);
                inputCase_ = 1;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getAudioInputFieldBuilder().getBuilder(),
                    extensionRegistry);
                inputCase_ = 2;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int inputCase_ = 0;
      private java.lang.Object input_;
      public InputCase
          getInputCase() {
        return InputCase.forNumber(
            inputCase_);
      }

      public Builder clearInput() {
        inputCase_ = 0;
        input_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          UserInputOuterClass.StringInput, UserInputOuterClass.StringInput.Builder, UserInputOuterClass.StringInputOrBuilder> stringInputBuilder_;
      /**
       * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
       * @return Whether the stringInput field is set.
       */
      @java.lang.Override
      public boolean hasStringInput() {
        return inputCase_ == 1;
      }
      /**
       * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
       * @return The stringInput.
       */
      @java.lang.Override
      public UserInputOuterClass.StringInput getStringInput() {
        if (stringInputBuilder_ == null) {
          if (inputCase_ == 1) {
            return (UserInputOuterClass.StringInput) input_;
          }
          return UserInputOuterClass.StringInput.getDefaultInstance();
        } else {
          if (inputCase_ == 1) {
            return stringInputBuilder_.getMessage();
          }
          return UserInputOuterClass.StringInput.getDefaultInstance();
        }
      }
      /**
       * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
       */
      public Builder setStringInput(UserInputOuterClass.StringInput value) {
        if (stringInputBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          input_ = value;
          onChanged();
        } else {
          stringInputBuilder_.setMessage(value);
        }
        inputCase_ = 1;
        return this;
      }
      /**
       * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
       */
      public Builder setStringInput(
          UserInputOuterClass.StringInput.Builder builderForValue) {
        if (stringInputBuilder_ == null) {
          input_ = builderForValue.build();
          onChanged();
        } else {
          stringInputBuilder_.setMessage(builderForValue.build());
        }
        inputCase_ = 1;
        return this;
      }
      /**
       * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
       */
      public Builder mergeStringInput(UserInputOuterClass.StringInput value) {
        if (stringInputBuilder_ == null) {
          if (inputCase_ == 1 &&
              input_ != UserInputOuterClass.StringInput.getDefaultInstance()) {
            input_ = UserInputOuterClass.StringInput.newBuilder((UserInputOuterClass.StringInput) input_)
                .mergeFrom(value).buildPartial();
          } else {
            input_ = value;
          }
          onChanged();
        } else {
          if (inputCase_ == 1) {
            stringInputBuilder_.mergeFrom(value);
          } else {
            stringInputBuilder_.setMessage(value);
          }
        }
        inputCase_ = 1;
        return this;
      }
      /**
       * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
       */
      public Builder clearStringInput() {
        if (stringInputBuilder_ == null) {
          if (inputCase_ == 1) {
            inputCase_ = 0;
            input_ = null;
            onChanged();
          }
        } else {
          if (inputCase_ == 1) {
            inputCase_ = 0;
            input_ = null;
          }
          stringInputBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
       */
      public UserInputOuterClass.StringInput.Builder getStringInputBuilder() {
        return getStringInputFieldBuilder().getBuilder();
      }
      /**
       * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
       */
      @java.lang.Override
      public UserInputOuterClass.StringInputOrBuilder getStringInputOrBuilder() {
        if ((inputCase_ == 1) && (stringInputBuilder_ != null)) {
          return stringInputBuilder_.getMessageOrBuilder();
        } else {
          if (inputCase_ == 1) {
            return (UserInputOuterClass.StringInput) input_;
          }
          return UserInputOuterClass.StringInput.getDefaultInstance();
        }
      }
      /**
       * <code>.StringInput stringInput = 1 [json_name = "stringInput"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserInputOuterClass.StringInput, UserInputOuterClass.StringInput.Builder, UserInputOuterClass.StringInputOrBuilder> 
          getStringInputFieldBuilder() {
        if (stringInputBuilder_ == null) {
          if (!(inputCase_ == 1)) {
            input_ = UserInputOuterClass.StringInput.getDefaultInstance();
          }
          stringInputBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserInputOuterClass.StringInput, UserInputOuterClass.StringInput.Builder, UserInputOuterClass.StringInputOrBuilder>(
                  (UserInputOuterClass.StringInput) input_,
                  getParentForChildren(),
                  isClean());
          input_ = null;
        }
        inputCase_ = 1;
        onChanged();
        return stringInputBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          UserInputOuterClass.AudioInput, UserInputOuterClass.AudioInput.Builder, UserInputOuterClass.AudioInputOrBuilder> audioInputBuilder_;
      /**
       * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
       * @return Whether the audioInput field is set.
       */
      @java.lang.Override
      public boolean hasAudioInput() {
        return inputCase_ == 2;
      }
      /**
       * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
       * @return The audioInput.
       */
      @java.lang.Override
      public UserInputOuterClass.AudioInput getAudioInput() {
        if (audioInputBuilder_ == null) {
          if (inputCase_ == 2) {
            return (UserInputOuterClass.AudioInput) input_;
          }
          return UserInputOuterClass.AudioInput.getDefaultInstance();
        } else {
          if (inputCase_ == 2) {
            return audioInputBuilder_.getMessage();
          }
          return UserInputOuterClass.AudioInput.getDefaultInstance();
        }
      }
      /**
       * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
       */
      public Builder setAudioInput(UserInputOuterClass.AudioInput value) {
        if (audioInputBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          input_ = value;
          onChanged();
        } else {
          audioInputBuilder_.setMessage(value);
        }
        inputCase_ = 2;
        return this;
      }
      /**
       * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
       */
      public Builder setAudioInput(
          UserInputOuterClass.AudioInput.Builder builderForValue) {
        if (audioInputBuilder_ == null) {
          input_ = builderForValue.build();
          onChanged();
        } else {
          audioInputBuilder_.setMessage(builderForValue.build());
        }
        inputCase_ = 2;
        return this;
      }
      /**
       * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
       */
      public Builder mergeAudioInput(UserInputOuterClass.AudioInput value) {
        if (audioInputBuilder_ == null) {
          if (inputCase_ == 2 &&
              input_ != UserInputOuterClass.AudioInput.getDefaultInstance()) {
            input_ = UserInputOuterClass.AudioInput.newBuilder((UserInputOuterClass.AudioInput) input_)
                .mergeFrom(value).buildPartial();
          } else {
            input_ = value;
          }
          onChanged();
        } else {
          if (inputCase_ == 2) {
            audioInputBuilder_.mergeFrom(value);
          } else {
            audioInputBuilder_.setMessage(value);
          }
        }
        inputCase_ = 2;
        return this;
      }
      /**
       * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
       */
      public Builder clearAudioInput() {
        if (audioInputBuilder_ == null) {
          if (inputCase_ == 2) {
            inputCase_ = 0;
            input_ = null;
            onChanged();
          }
        } else {
          if (inputCase_ == 2) {
            inputCase_ = 0;
            input_ = null;
          }
          audioInputBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
       */
      public UserInputOuterClass.AudioInput.Builder getAudioInputBuilder() {
        return getAudioInputFieldBuilder().getBuilder();
      }
      /**
       * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
       */
      @java.lang.Override
      public UserInputOuterClass.AudioInputOrBuilder getAudioInputOrBuilder() {
        if ((inputCase_ == 2) && (audioInputBuilder_ != null)) {
          return audioInputBuilder_.getMessageOrBuilder();
        } else {
          if (inputCase_ == 2) {
            return (UserInputOuterClass.AudioInput) input_;
          }
          return UserInputOuterClass.AudioInput.getDefaultInstance();
        }
      }
      /**
       * <code>.AudioInput audioInput = 2 [json_name = "audioInput"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserInputOuterClass.AudioInput, UserInputOuterClass.AudioInput.Builder, UserInputOuterClass.AudioInputOrBuilder> 
          getAudioInputFieldBuilder() {
        if (audioInputBuilder_ == null) {
          if (!(inputCase_ == 2)) {
            input_ = UserInputOuterClass.AudioInput.getDefaultInstance();
          }
          audioInputBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserInputOuterClass.AudioInput, UserInputOuterClass.AudioInput.Builder, UserInputOuterClass.AudioInputOrBuilder>(
                  (UserInputOuterClass.AudioInput) input_,
                  getParentForChildren(),
                  isClean());
          input_ = null;
        }
        inputCase_ = 2;
        onChanged();
        return audioInputBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:UserInput)
    }

    // @@protoc_insertion_point(class_scope:UserInput)
    private static final UserInputOuterClass.UserInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInputOuterClass.UserInput();
    }

    public static UserInputOuterClass.UserInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInput>
        PARSER = new com.google.protobuf.AbstractParser<UserInput>() {
      @java.lang.Override
      public UserInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UserInputOuterClass.UserInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInputResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserInputResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return The success.
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code UserInputResponse}
   */
  public static final class UserInputResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserInputResponse)
      UserInputResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        UserInputResponse.class.getName());
    }
    // Use UserInputResponse.newBuilder() to construct.
    private UserInputResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserInputResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserInputOuterClass.internal_static_UserInputResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserInputOuterClass.internal_static_UserInputResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserInputOuterClass.UserInputResponse.class, UserInputOuterClass.UserInputResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_ = false;
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserInputOuterClass.UserInputResponse)) {
        return super.equals(obj);
      }
      UserInputOuterClass.UserInputResponse other = (UserInputOuterClass.UserInputResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserInputOuterClass.UserInputResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.UserInputResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.UserInputResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.UserInputResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.UserInputResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.UserInputResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.UserInputResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserInputOuterClass.UserInputResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserInputOuterClass.UserInputResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserInputOuterClass.UserInputResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserInputOuterClass.UserInputResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserInputOuterClass.UserInputResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserInputOuterClass.UserInputResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserInputResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserInputResponse)
        UserInputOuterClass.UserInputResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserInputOuterClass.internal_static_UserInputResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserInputOuterClass.internal_static_UserInputResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserInputOuterClass.UserInputResponse.class, UserInputOuterClass.UserInputResponse.Builder.class);
      }

      // Construct using UserInputOuterClass.UserInputResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        success_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserInputOuterClass.internal_static_UserInputResponse_descriptor;
      }

      @java.lang.Override
      public UserInputOuterClass.UserInputResponse getDefaultInstanceForType() {
        return UserInputOuterClass.UserInputResponse.getDefaultInstance();
      }

      @java.lang.Override
      public UserInputOuterClass.UserInputResponse build() {
        UserInputOuterClass.UserInputResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UserInputOuterClass.UserInputResponse buildPartial() {
        UserInputOuterClass.UserInputResponse result = new UserInputOuterClass.UserInputResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(UserInputOuterClass.UserInputResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.success_ = success_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserInputOuterClass.UserInputResponse) {
          return mergeFrom((UserInputOuterClass.UserInputResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserInputOuterClass.UserInputResponse other) {
        if (other == UserInputOuterClass.UserInputResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                success_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>bool success = 1 [json_name = "success"];</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1 [json_name = "success"];</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1 [json_name = "success"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UserInputResponse)
    }

    // @@protoc_insertion_point(class_scope:UserInputResponse)
    private static final UserInputOuterClass.UserInputResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInputOuterClass.UserInputResponse();
    }

    public static UserInputOuterClass.UserInputResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInputResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserInputResponse>() {
      @java.lang.Override
      public UserInputResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserInputResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInputResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UserInputOuterClass.UserInputResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StringInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StringInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code StringInput}
   */
  public static final class StringInput extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:StringInput)
      StringInputOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        StringInput.class.getName());
    }
    // Use StringInput.newBuilder() to construct.
    private StringInput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StringInput() {
      value_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserInputOuterClass.internal_static_StringInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserInputOuterClass.internal_static_StringInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserInputOuterClass.StringInput.class, UserInputOuterClass.StringInput.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserInputOuterClass.StringInput)) {
        return super.equals(obj);
      }
      UserInputOuterClass.StringInput other = (UserInputOuterClass.StringInput) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserInputOuterClass.StringInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.StringInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.StringInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.StringInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.StringInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.StringInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.StringInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserInputOuterClass.StringInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserInputOuterClass.StringInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserInputOuterClass.StringInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserInputOuterClass.StringInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserInputOuterClass.StringInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserInputOuterClass.StringInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StringInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StringInput)
        UserInputOuterClass.StringInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserInputOuterClass.internal_static_StringInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserInputOuterClass.internal_static_StringInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserInputOuterClass.StringInput.class, UserInputOuterClass.StringInput.Builder.class);
      }

      // Construct using UserInputOuterClass.StringInput.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        value_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserInputOuterClass.internal_static_StringInput_descriptor;
      }

      @java.lang.Override
      public UserInputOuterClass.StringInput getDefaultInstanceForType() {
        return UserInputOuterClass.StringInput.getDefaultInstance();
      }

      @java.lang.Override
      public UserInputOuterClass.StringInput build() {
        UserInputOuterClass.StringInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UserInputOuterClass.StringInput buildPartial() {
        UserInputOuterClass.StringInput result = new UserInputOuterClass.StringInput(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(UserInputOuterClass.StringInput result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.value_ = value_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserInputOuterClass.StringInput) {
          return mergeFrom((UserInputOuterClass.StringInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserInputOuterClass.StringInput other) {
        if (other == UserInputOuterClass.StringInput.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1 [json_name = "value"];</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:StringInput)
    }

    // @@protoc_insertion_point(class_scope:StringInput)
    private static final UserInputOuterClass.StringInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInputOuterClass.StringInput();
    }

    public static UserInputOuterClass.StringInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StringInput>
        PARSER = new com.google.protobuf.AbstractParser<StringInput>() {
      @java.lang.Override
      public StringInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StringInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StringInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UserInputOuterClass.StringInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AudioInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AudioInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code AudioInput}
   */
  public static final class AudioInput extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AudioInput)
      AudioInputOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        AudioInput.class.getName());
    }
    // Use AudioInput.newBuilder() to construct.
    private AudioInput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AudioInput() {
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserInputOuterClass.internal_static_AudioInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserInputOuterClass.internal_static_AudioInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserInputOuterClass.AudioInput.class, UserInputOuterClass.AudioInput.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes value = 1 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!value_.isEmpty()) {
        output.writeBytes(1, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserInputOuterClass.AudioInput)) {
        return super.equals(obj);
      }
      UserInputOuterClass.AudioInput other = (UserInputOuterClass.AudioInput) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserInputOuterClass.AudioInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.AudioInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.AudioInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.AudioInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.AudioInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInputOuterClass.AudioInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInputOuterClass.AudioInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserInputOuterClass.AudioInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserInputOuterClass.AudioInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserInputOuterClass.AudioInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserInputOuterClass.AudioInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserInputOuterClass.AudioInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserInputOuterClass.AudioInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AudioInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AudioInput)
        UserInputOuterClass.AudioInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserInputOuterClass.internal_static_AudioInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserInputOuterClass.internal_static_AudioInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserInputOuterClass.AudioInput.class, UserInputOuterClass.AudioInput.Builder.class);
      }

      // Construct using UserInputOuterClass.AudioInput.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        value_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserInputOuterClass.internal_static_AudioInput_descriptor;
      }

      @java.lang.Override
      public UserInputOuterClass.AudioInput getDefaultInstanceForType() {
        return UserInputOuterClass.AudioInput.getDefaultInstance();
      }

      @java.lang.Override
      public UserInputOuterClass.AudioInput build() {
        UserInputOuterClass.AudioInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UserInputOuterClass.AudioInput buildPartial() {
        UserInputOuterClass.AudioInput result = new UserInputOuterClass.AudioInput(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(UserInputOuterClass.AudioInput result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.value_ = value_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserInputOuterClass.AudioInput) {
          return mergeFrom((UserInputOuterClass.AudioInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserInputOuterClass.AudioInput other) {
        if (other == UserInputOuterClass.AudioInput.getDefaultInstance()) return this;
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                value_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 1 [json_name = "value"];</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 1 [json_name = "value"];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 1 [json_name = "value"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AudioInput)
    }

    // @@protoc_insertion_point(class_scope:AudioInput)
    private static final UserInputOuterClass.AudioInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInputOuterClass.AudioInput();
    }

    public static UserInputOuterClass.AudioInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AudioInput>
        PARSER = new com.google.protobuf.AbstractParser<AudioInput>() {
      @java.lang.Override
      public AudioInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AudioInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AudioInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UserInputOuterClass.AudioInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInputResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserInputResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StringInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StringInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AudioInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AudioInput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017userInput.proto\"u\n\tUserInput\0220\n\013string" +
      "Input\030\001 \001(\0132\014.StringInputH\000R\013stringInput" +
      "\022-\n\naudioInput\030\002 \001(\0132\013.AudioInputH\000R\naud" +
      "ioInputB\007\n\005input\"-\n\021UserInputResponse\022\030\n" +
      "\007success\030\001 \001(\010R\007success\"#\n\013StringInput\022\024" +
      "\n\005value\030\001 \001(\tR\005value\"\"\n\nAudioInput\022\024\n\005va" +
      "lue\030\001 \001(\014R\005valueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserInput_descriptor,
        new java.lang.String[] { "StringInput", "AudioInput", "Input", });
    internal_static_UserInputResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserInputResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserInputResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_StringInput_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StringInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StringInput_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_AudioInput_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AudioInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AudioInput_descriptor,
        new java.lang.String[] { "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
